version: '3.8'

services:
  user-service:
    build: ./UserService
    container_name: user-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - aquamanage-network

  tank-service:
    build: ./TankService
    container_name: tank-service
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - aquamanage-network

  actuator-service:
    build: ./ActuatorService
    container_name: actuator-service
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - aquamanage-network

  sensor-service:
    build: ./SensorService
    container_name: sensor-service
    ports:
      - "8084:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - aquamanage-network

networks:
  aquamanage-network:
    driver: bridge
