version: '3.8'

services:
  userservice-db:
    image: postgres:13
    container_name: userservice-db
    environment:
      POSTGRES_DB: userservice
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mine
    ports:
      - "5433:5432"
    volumes:
      - userservice_data:/var/lib/postgresql/data
    networks:
      - aquamanage-network

  user-service:
    build: ./UserService
    container_name: user-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://userservice-db:5432/userservice
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=mine
    depends_on:
      - userservice-db
    networks:
      - aquamanage-network

  tank-service:
    build: ./TankService
    container_name: tank-service
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - aquamanage-network

  actuator-service:
    build: ./ActuatorService
    container_name: actuator-service
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - aquamanage-network

  sensor-service:
    build: ./SensorService
    container_name: sensor-service
    ports:
      - "8084:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - aquamanage-network

networks:
  aquamanage-network:
    driver: bridge

volumes:
  userservice_data: