server:
  port: 8080

spring:
  application:
    name: UserService

  datasource:
    url: jdbc:postgresql://localhost:5432/userservice
    username: postgres
    password: mine
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  sql:
    init:
      mode: always

logging:
  level:
    root: WARN
    org.springframework.web: DEBUG
    org.hibernate: ERROR
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE