spring:
  application:
    name: TankService


  datasource:
    url: jdbc:postgresql://localhost:5432/aquamanage
    username: postgres
    password: mine
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          database-platform: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
          show_sql: true
